qa_pairs = [
    {"question": "What is BIMS portal?", "answer": "BIMS portal is a platform for final year students to manage, submit, and track their project progress."},
    {"question": "How can I login?", "answer": "You can login using your student or teacher credentials provided by the institution."},
    {"question": "How to reset password?", "answer": "Click on \"Forgot Password\" and follow the instructions."},
    {"question": "What can I do on student dashboard?", "answer": "You can upload projects, track progress, view deadlines, and receive notifications."},
    {"question": "How to upload project?", "answer": "Go to dashboard → click upload → select file → submit."},
    {"question": "How to check my progress?", "answer": "Progress is shown in percentage on your dashboard."},
    {"question": "How does progress tracking work?", "answer": "The system compares your uploaded work with the given template."},
    {"question": "Why is my progress low?", "answer": "Your work may not match the required template."},
    {"question": "How to improve progress?", "answer": "Follow the template guidelines carefully."},
    {"question": "What can teachers do on portal?", "answer": "Teachers can assign tasks, review work, and give feedback."},
    {"question": "Can teachers edit files?", "answer": "Yes, teachers can highlight errors directly on the portal."},
    {"question": "How do I get updates?", "answer": "Notifications appear on your dashboard."},
    {"question": "Will I get deadline reminders?", "answer": "Yes, the system sends reminders before deadlines."},
    {"question": "Where can I see my tasks?", "answer": "Tasks are available in your dashboard."},
    {"question": "How to submit assigned task?", "answer": "Upload your work in the assigned task section."},
    {"question": "What can Chabot do?", "answer": "It helps answer your queries when no human is available."},
    {"question": "Can Chabot solve all problems?", "answer": "It can answer basic questions only."},
    {"question": "Where can I find project ideas?", "answer": "You can find them in the \"Project Ideas\" section."},
    {"question": "Hi?", "answer": "Hi, How may i help you?."},
    {"question": "Are previous projects available?", "answer": "Yes, previous project links are available."},
    {"question": "Can I update my profile?", "answer": "Yes, you can edit your profile in settings."},
    {"question": "Why is my file not uploading?", "answer": "Check file format and size."},
    {"question": "What file formats are allowed?", "answer": "PDF, DOCX, PPT."},
    {"question": "Can I resubmit my work?", "answer": "Yes, after teacher feedback."},
    {"question": "How to resubmit?", "answer": "Upload updated file again."},
    {"question": "Why errors are highlighted?", "answer": "To help you correct mistakes."},
    {"question": "How to fix errors?", "answer": "Follow teacher comments."},
    {"question": "Is my data safe?", "answer": "Yes, your data is securely stored."},
    {"question": "Can I access portal anytime?", "answer": "Yes, it is available 24/7."},
    {"question": "How to contact support?", "answer": "Use help section or contact admin."},
    {"question": "What if Chabot doesn't help?", "answer": "You can contact your teacher or admin."},
    {"question": "How do I view teacher feedback?", "answer": "Open your submission and check the feedback panel on the project page."},
    {"question": "Can I upload a draft version of my project?", "answer": "Yes, upload your draft in the draft or submission section before the final due date."},
    {"question": "How can I download my submission?", "answer": "Go to your project submission details and click the download button for your file."},
    {"question": "What should I do if my deadline is extended?", "answer": "Check the task update message, then upload the new work before the extended deadline."},
    {"question": "How do I change my password?", "answer": "Go to settings, select password change, and follow the instructions."},
    {"question": "How can I see new announcements?", "answer": "Announcements appear on the dashboard and in the notification area."},
    {"question": "What is the project template?", "answer": "The template is a document or format given by teachers that you must follow for your project and report."},
    {"question": "How do I submit my presentation file?", "answer": "Upload your presentation in the assigned task section under the correct file type."},
    {"question": "Can teachers assign group projects?", "answer": "Yes, teachers can create group tasks and assign students together."},
    {"question": "How do I see previous project ideas?", "answer": "Visit the Project Ideas section and browse the list with links to past projects."},
    {"question": "How can I update my team members?", "answer": "Ask your teacher or admin to update team details, then reflect the changes in the portal if allowed."}
]